INSERT INTO BOOK(BOOK_NAME,BOOK_TYPE,BOOK_AUTHOR,NO_OF_PAGES) VALUES('Book 1','Type 1', 'Author 1', 100);
INSERT INTO BOOK(BOOK_NAME,BOOK_TYPE,BOOK_AUTHOR,NO_OF_PAGES) VALUES('Book 2','Type 2', 'Author 2', 200);
INSERT INTO BOOK(BOOK_NAME,BOOK_TYPE,BOOK_AUTHOR,NO_OF_PAGES) VALUES('Book 3','Type 3', 'Author 3', 300);
INSERT INTO BOOK(BOOK_NAME,BOOK_TYPE,BOOK_AUTHOR,NO_OF_PAGES) VALUES('Book 4','Type 4', 'Author 4', 400);
INSERT INTO BOOK(BOOK_NAME,BOOK_TYPE,BOOK_AUTHOR,NO_OF_PAGES) VALUES('Book 5','Type 5', 'Author 5', 500);
INSERT INTO BOOK(BOOK_NAME,BOOK_TYPE,BOOK_AUTHOR,NO_OF_PAGES) VALUES('Book 6','Type 6', 'Author 6', 600);
INSERT INTO BOOK(BOOK_NAME,BOOK_TYPE,BOOK_AUTHOR,NO_OF_PAGES) VALUES('Book 7','Type 7', 'Author 7', 700);